In [1]:
import pathlib

import pandas as pd
from pycytominer import normalize
from pycytominer.cyto_utils import output

In [2]:
# set path to data

combined_data_path = pathlib.Path(
    "../data/CP_scDINO_features/combined_CP_scDINO_data.parquet"
).resolve(strict=True)

# set output path
normalized_data_output_path = pathlib.Path(
    "../data/CP_scDINO_features/combined_CP_scDINO_norm.parquet"
).resolve()

# load data
combined_data = pd.read_parquet(combined_data_path)
print(combined_data.shape)
combined_data.head()

(188065, 3874)

,Metadata_plate,Metadata_Well,Metadata_number_of_singlecells,Metadata_compound,Metadata_dose,Metadata_control,Metadata_ImageNumber,Metadata_FOV,Metadata_Time,Metadata_Cells_Number_Object_Number,...,channel_DNA_cls_feature_90_scDINO,channel_DNA_cls_feature_91_scDINO,channel_DNA_cls_feature_92_scDINO,channel_DNA_cls_feature_93_scDINO,channel_DNA_cls_feature_94_scDINO,channel_DNA_cls_feature_95_scDINO,channel_DNA_cls_feature_96_scDINO,channel_DNA_cls_feature_97_scDINO,channel_DNA_cls_feature_98_scDINO,channel_DNA_cls_feature_99_scDINO
0,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,6,...,-0.036293,-0.015376,-0.043500,0.014685,-0.075158,-0.016355,0.024915,0.021255,0.040291,-0.008547
1,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,7,...,0.006480,-0.032704,-0.058273,0.035836,-0.111744,-0.013086,0.004745,0.022615,0.070535,-0.003347
2,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,10,...,-0.026490,-0.015176,-0.005187,0.054708,-0.087279,-0.000325,-0.001391,0.037920,0.053616,-0.011323
3,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,11,...,-0.025042,-0.030499,-0.059684,0.018545,-0.054861,-0.014672,0.002961,-0.012981,0.066953,-0.002840
4,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,12,...,0.016725,-0.006152,0.004484,0.042892,-0.102706,0.057919,-0.002141,0.010048,0.006700,0.013923

In [3]:
# Get columns that contain "Metadata"
metadata_features = combined_data.columns[
    combined_data.columns.str.contains("Metadata")
].tolist()

# get the feature columns
feature_columns = combined_data.columns.difference(metadata_features).to_list()

In [4]:
# Normalize the single cell data per time point

# get the unique time points
time_points = combined_data.Metadata_Time.unique()

output_dict_of_normalized_dfs = {}

# normalize annotated data
normalized_df = normalize(
    # df with annotated raw merged single cell features
    profiles=combined_data,
    features=feature_columns,
    meta_features=metadata_features,
    # specify samples used as normalization reference (negative control)
    samples="Metadata_compound == 'Staurosporine' and Metadata_dose == '0.0' and Metadata_Time == '0.0'",
    # normalization method used
    method="standardize",
)

output(
    normalized_df,
    output_filename=normalized_data_output_path,
    output_type="parquet",
)
print("Single cells have been normalized!")
# check to see if the features have been normalized
print(normalized_df.shape)
normalized_df.head()

Single cells have been normalized!
(188065, 3874)

,Metadata_plate,Metadata_Well,Metadata_number_of_singlecells,Metadata_compound,Metadata_dose,Metadata_control,Metadata_ImageNumber,Metadata_FOV,Metadata_Time,Metadata_Cells_Number_Object_Number,...,channel_DNA_cls_feature_91_scDINO,channel_DNA_cls_feature_92_scDINO,channel_DNA_cls_feature_93_scDINO,channel_DNA_cls_feature_94_scDINO,channel_DNA_cls_feature_95_scDINO,channel_DNA_cls_feature_96_scDINO,channel_DNA_cls_feature_97_scDINO,channel_DNA_cls_feature_98_scDINO,channel_DNA_cls_feature_99_scDINO,channel_DNA_cls_feature_9_scDINO
0,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,6,...,-0.421030,-0.639528,-1.108697,0.508837,-1.180882,0.521719,0.419948,-0.254621,0.140152,-0.311706
1,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,7,...,-1.118932,-1.264854,0.263361,-0.473379,-1.034858,-0.412041,0.470434,0.819060,0.522236,-2.358482
2,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,10,...,-0.413004,0.982228,1.487644,0.183418,-0.464693,-0.696133,1.038610,0.218406,-0.063818,-1.270270
3,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,11,...,-1.030118,-1.324591,-0.858296,1.053740,-1.105719,-0.494646,-0.851002,0.691902,0.559527,0.201144
4,1,C-10,156,Staurosporine,78.13,test,1,0003,0.0,12,...,-0.049551,1.391577,0.721089,-0.230744,2.137543,-0.730854,0.003878,-1.447163,1.791341,-0.927917